urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth.views import logout_then_login
from django.conf import settings


# Uncomment the next two lines to enable the admin:
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^t/(.+)$', 'transition.views.qrcode'),
                       url(r'^testtag/$', 'transition.views.test_tag'),
                       url(r'^registertag/(.*)$', 'transition.views.register_tag'),
                       url(r'^foundtag/(.*)$', 'transition.views.found_tag'),
                       url(r'^myrockettags$', 'transition.views.myrockettags'),
                       url(r'^user_logout/$', 'transition.views.user_logout'),
                       url(r'^login$', 'transition.views.login_'),
                       url(r'^$', 'transition.views.home'),
                       url(r'^googlecb48235008046c8e.html/$', 'transition.views.google_seo'),
                       url(r'^reset/$', 'transition.views.reset'),
                       url(r'^check/$', 'transition.views.check'),
                       url(r'^trainingvideo/$', 'transition.views.trainingvideo'),
                       url(r'^promo$', 'transition.views.redirect_to_promo_offer'),
                       url(r'^promo/offer$', 'transition.views.promo'),
                       url(r'^promo-thankyou$', 'transition.views.promo_thankyou'),
                       url(r'^cam01$', 'transition.views.cam01'),
                       url(r'^bulk-test$', 'transition.views.bulk_test'),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^corp_promo', 'transition.views.corp_promo'),
                       url(r'^corp_solutions', 'transition.views.corp_solutions'),
                       url(r'^sheetapp', 'sheetapp.views.main'),
                       url(r'^corpmanage', 'sheetapp.views.corpmanage'),
                       url(r'^updatetag', 'sheetapp.views.updatetag'),
                       url(r'^downloadmytags', 'sheetapp.views.downloadmytags'),
                       url(r'^emailmyeditedtags', 'sheetapp.views.emailmyeditedtags'),
                       url(r'^updatecustomfields', 'sheetapp.views.updatecustomfields'),
                       url(r'^renamefields', 'sheetapp.views.renamefields'),
                       url(r'^staffconsole', 'sheetapp.views.staffconsole'),
                       url(r'^createcorporateaccount', 'sheetapp.views.createcorporateaccount'),
                       url(r'^uploadtags', 'sheetapp.views.uploadtags'),
                       url(r'^landing', 'transition.views.facebooklanding'),
                       )

urlpatterns += patterns('',
                        url(r'^captcha/', include('captcha.urls')),
                        )

"""
url(r'^testcaptcha/$', 'transition.views.test_captcha'),
url(r'^reset/$', 'transition.views.reset'),
url(r'^gettags/$', 'transition.views.get_tags'),
url(r'^user/$', 'transition.views.userinfo'),
url(r'^test_menu/$', direct_to_template, {'template': 'transition/test_menu.html'} ), 
"""

transition/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from django.conf import settings
import pytz


class TestTag(models.Model):
    code = models.CharField(null=False, blank=False, unique=True, max_length=8)

    def __unicode__(self):
        return u'%s' % self.code


class Tag(models.Model):
    code = models.CharField(null=False, blank=False, unique=True, max_length=8)
    user = models.ForeignKey(User, null=True, blank=True, related_name='tags', on_delete=models.SET_NULL)
    issued_date = models.DateTimeField(default=None)
    registered_date = models.DateTimeField(null=True, blank=True)
    edit_time = models.DateTimeField(default=None, null=True)
    assigned_to = models.EmailField(null=True, blank=True)
    status = models.PositiveIntegerField(default=0)  # 0 - not registered, 1 = registered
    tag_type = models.PositiveIntegerField(default=0)  # 0 - GENERATED, 1 = STANDARD, etc.
    product_id = models.IntegerField(null=True)
    batch_num = models.IntegerField(null=True)
    email_cc = models.BooleanField(default=True)
    field1 = models.CharField(null=True, default=None, max_length=255)
    field2 = models.CharField(null=True, default=None, max_length=255)
    field3 = models.CharField(null=True, default=None, max_length=255)
    field4 = models.CharField(null=True, default=None, max_length=255)

    def to_base36(self):
        val = self.code
        result = val
        return result

    to_base36.short_description = 'Tag ID'

    def __unicode__(self):
        return u'%s' % self.to_base36()

    # Factory Methods for creating Tags

    @classmethod
    def create(cls, tagcode=None):
        if tagcode is None:
            return cls.create_from_random()
        else:
            return cls.create_from_given_code(tagcode)

    @classmethod
    def create_from_random(cls):
        newtagcode = cls.generate_tagcode()
        newtag = Tag(code=newtagcode)
        newtag.issued_date = datetime.now()
        return newtag

    @classmethod
    def generate_tagcode(cls):
        maxnumber = pow(2, 32)

        randomnum = random.randint(1, maxnumber)
        randomtag = cls.convert_to_base36(randomnum)

        while cls.exists(randomtag) or not cls.is_valid(randomtag):
            randomnum = random.randint(1, maxnumber)
            randomtag = cls.convert_to_base36(randomnum)

        return randomtag

    @classmethod
    def create_from_given_code(cls, newtagcode):
        # don't accept if the tagcode is not valid or is offensive
        if not cls.is_valid(newtagcode) or cls.has_offensive_word(newtagcode):
            return None
        # don't accept if the tagid is already assigned
        if cls.exists(newtagcode):
            return None
        newtag = Tag(code=newtagcode)
        newtag.issued_date = datetime.now()
        return newtag

    # Extension to get method for locating by base36 tagcode
    @classmethod
    def get_from_base36(cls, tagcode):
        found_tag = cls.objects.get(code=tagcode)
        return found_tag

    # Utility methods for converting between decimal and base36

    @classmethod
    def convert_to_base36(cls, val):
        result = ''
        temp = []
        while val >= 36:
            div = val / 36
            mod = val % 36
            temp.append(mod)
            val = div
        temp.append(val)

        while len(temp) > 0:
            digit = temp.pop()
            if digit > 9:
                result = '%s%s' % (result, chr(digit + 55))
            else:
                result = '%s%s' % (result, digit)
        return result

    @classmethod
    def convert_from_base36(cls, val):
        return int(val, 36)

    # Validation methods

    @classmethod
    def is_valid(cls, tagcode):
        if len(tagcode) > 7:
            return False
        elif not re.search('([AEIOU]+)', tagcode) is None:
            return False
        elif not re.search('([0-9BCDFGHJKLMNPQRSTVWXYZ]{1,8})', tagcode) is None:
            tagvalue = cls.convert_from_base36(tagcode)
            if tagvalue <= pow(2, 32): return True
        return False

    @classmethod
    def has_offensive_word(cls, tagcode):
        for word in bad_words.offensive_words:
            pattern = '.*%s.*' % word
            if re.search(pattern, tagcode):
                return word
        return None

    @classmethod
    def exists(cls, tagcode):
        try:
            existing_tag = cls.objects.get(code=tagcode)
        except:
            existing_tag = None
        if existing_tag is not None:
            return True
        return False

    @classmethod
    def create_pool(cls, request, poolsize, tag_type=0):

        if poolsize == 0:
            return None

        tags = []
        for i in range(0, poolsize):
            new_tag = cls.create()
            new_tag.tag_type = tag_type
            new_tag.save()

            # rockettags.main.models.create_log_entry('Generated tag code', 'Generated new tag code %s; number %d of 15; internal id %d' % (new_tag.to_base36(), i+1, new_tag.id), tablename='Tag')

            tags.append(new_tag)

        return tags

    @classmethod
    def obtain_pool(cls, request, poolsize, start_tag_id, end_tag_id):

        tags = cls.objects.all()[start_tag_id - 1:end_tag_id]

        return tags

    @classmethod
    def obtain_pool_of_codes(cls, request, poolsize, start_tag_id, end_tag_id):

        tags = cls.objects.all()[start_tag_id - 1:end_tag_id]

        tagcodes = []
        for current_tag in tags:
            # rockettags.main.models.create_log_entry('Obtained tag code', 'Obtained existing tag code %s; number %d of 15; internal id %d' % (current_tag.to_base36(), i+1, current_tag.id), tablename='Tag')

            tagcode = current_tag.to_base36()

            tagcodes.append(tagcode)

        return tagcodes

    @classmethod
    def update_pool_tag_type(cls, request, start_tag_id, end_tag_id, new_tag_type):

        tags = cls.objects.all()[start_tag_id - 1:end_tag_id]

        for atag in tags:
            atag.tag_type = new_tag_type
            atag.save()

        return tags

    @classmethod
    def update_tag_type_by_code(cls, request, tag_code, new_tag_type):

        atag = cls.objects.get(code=tag_code)

        if not atag is None:
            atag.tag_type = new_tag_type
            atag.save()

        return atag


class FoundMessage(models.Model):
    tag = models.ForeignKey(Tag, related_name='messages', null=True, blank=True, on_delete=models.SET_NULL)
    email = models.EmailField(max_length=128, blank=True, null=True)
    phone = models.CharField(max_length=20, blank=True, null=True)
    firstname = models.CharField(max_length=128, blank=True, null=True)
    lastname = models.CharField(max_length=128, blank=True, null=True)
    address = models.CharField(max_length=255, blank=True, null=True)
    city = models.CharField(max_length=64, blank=True, null=True)
    state = models.CharField(max_length=64, blank=True, null=True)
    country = models.CharField(max_length=5, blank=True, null=True)
    contact_method = models.CharField(max_length=255, blank=True, null=True)
    item_description = models.CharField(max_length=255, blank=True, null=True)
    item_location = models.CharField(max_length=255, blank=True, null=True)
    message = models.CharField(max_length=255, blank=True, null=True)
    status = models.PositiveIntegerField(default=0)
    generated_date = models.DateTimeField(default=None)
    completed = models.BooleanField(default=False)
    acted_upon_date = models.DateTimeField(null=True, blank=True)


class Subscription(models.Model):
    user = models.ForeignKey(User)
    autorenew = models.PositiveIntegerField(default=0)
    period = models.PositiveIntegerField(default=0)
    creation_date = models.DateTimeField(default=None)
    expiry_date = models.DateTimeField(null=True, blank=True)
    extra1 = models.CharField(max_length=128, null=True, blank=True)  # reserved for future subscription id
    extra2 = models.CharField(max_length=64, null=True, blank=True)  # reserved for annotation about latest change
    extra3 = models.CharField(max_length=32, null=True,
                              blank=True)  # 25022013 reserved for whether or not T&Cs in version 2.0 have been accepted (when subscription happens without a payment)
    status = models.PositiveIntegerField(default=0)
    update_date = models.DateTimeField(null=True, blank=True)

    def __unicode__(self):
        return u'%s' % self.user_id


class UserProfile(models.Model):
    # This field is required.
    user = models.OneToOneField(User)

    # preferences
    tag_code = models.CharField(max_length=8, null=True, blank=True)
    tag_format = models.CharField(max_length=12, null=True,
                                  blank=True)  # 28072012 reserved as a flag for whether or not the user wants to be contactable (values are 0 for no, 1 for email)
    tag_colour = models.CharField(max_length=12, null=True,
                                  blank=True)  # 26072012 used for whether a user has been sent their promo for verifying their email
    subscription_period = models.IntegerField(default=0)

    # activation key - 26072012 used to hold whether or not a user has verified their email address
    # is either True or False. If empty or None is False.
    activation_key = models.CharField(max_length=40, null=True, blank=True)
    key_expires = models.DateTimeField(null=True, blank=True)

    # contact details
    # 28072012 These fields are no longer in use
    address1 = models.CharField(max_length=128, null=True, blank=True)
    address2 = models.CharField(max_length=128, null=True, blank=True)
    city = models.CharField(max_length=64, null=True, blank=True)
    state = models.CharField(max_length=64, null=True, blank=True)
    country = models.CharField(max_length=32, null=True, blank=True)
    postcode = models.CharField(max_length=32, null=True, blank=True)

main/forms.py
from django.utils.translation import ugettext_lazy as _
from django import forms
from django.contrib.auth.forms import AuthenticationForm

class LoginForm(AuthenticationForm) :
    email = forms.CharField(max_length=128)
    username = forms.CharField(label=_("Username"), max_length=128, required=False)

    # At some point do custom validation
    def is_valid(self) :
        return True

class LostCredentialsForm(forms.Form) :
    email = forms.CharField(max_length=128)
    username = forms.CharField(label=_("Username"), max_length=128, required=False)

    # At some point do custom validation
    def is_valid(self) :
        return True

class RegistrationForm(forms.Form) :
    email = forms.CharField(max_length=128)
    email2 = forms.CharField(label=_("E-mail (again)"), max_length=128, required=False)
    firstname = forms.CharField(max_length=128, required=False)
    lastname = forms.CharField(max_length=128, required=False)
    password1 = forms.CharField(max_length=128, required=True, widget=forms.PasswordInput)
    password2 = forms.CharField(max_length=128, required=True, widget=forms.PasswordInput)
    country = forms.CharField(max_length=3, required=False)
    state = forms.CharField(max_length=3, required=False)
    
    # At some point do custom validation
    def is_valid(self) :
        return True

class ConfirmationForm(forms.Form) :
    activation_key = forms.CharField(max_length=128, required=False)    
    email = forms.CharField(max_length=128, required=False)    
    password = forms.CharField(max_length=128, required=False, widget=forms.PasswordInput)
    
    # At some point do custom validation
    def is_valid(self) :
        return True

transition/templates/bulk-test.html
<table border="1">
<tr><td>Code</td><td>Issue Date</td><td>Registered Date</td><td>Status</td></tr>
{% for tag in tested %}
    <tr><td>{{ tag.code }}</td><td>{{ tag.issued_date }}</td><td>{{ tag.registered_date }}</td><td>{{ tag.status }}</td></tr>
{% endfor %}
</table>

transition/templates/corp_promo.html
{% extends "corp_base.html" %}

{% block content %}

<div class="row" style="margin-bottom:25px">
    <div class="span12">
        <img src="/static/img/corpA.jpg" >

    </div>
</div>

{% endblock content %}

transition/templates/found_tag_2.html
{% extends "base.html" %}

{% block content %}

<div class="wizard row">   
    <div class="span4">    
        <div>        
            <h1>are you <strong>human?</strong></h1>                             
            <p>We just need to check you're not a robot. Please complete the simple equation and click to proceed.</p>
        </div>
    </div>
    <div class="span8 orange_box tc">     
        <form action="" method="post">{% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        <div>
            {{ form.captcha }}
        </div>
        <div>
            <input type="image" name="submit" src="/static/img/Button_Ok Try That.png" alt="Submit" />
        </div>
        </form>
    </div>
</div>
{% endblock content %}

transition/templates/found_tag_3.html
{% extends "base.html" %}

{% block content %}

<div class="wizard row">   
    <div class="span4">
        <div>        
            <h1 style="margin: 0; padding: 0"><strong>Add more details</strong></h1>
            <h2>(optional)</h2>                             
            <p>Please add additional details if you wish.</p>
            <p>This is optional, if you are done just click 'im finished' to proceed.</p>
        </div>
    </div>
    <div id="found-tag-3" class="span8 orange_box tc">
        <form action="" method="post">{% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        <div>
            <h4><strong>YOUR DETAILS</strong></h4>
            <input maxlength="50" id="id_first_name" name="first_name"   type="text" placeholder="first name"/><br>
            <input maxlength="50"  id="id_last_name" style="margin-top: 7px"  name="last_name"  type="text" placeholder="last name"/><br>
            <input maxlength="100"  id="id_address" style="margin-top: 7px"  name="address"  type="text" placeholder="address"/><br>
            <input maxlength="50"  id="id_phone_number" style="margin-top: 7px"  name="phone_number"  type="text" placeholder="phone number"/><br>
            <select class="oj_combo" name="contact_method" style="margin: 7px 0 12px 0;" id="id_contact_method">
            <option value="" disabled selected>preferred contact method</option>
            <option value="email">email</option>
            <option value="phone call">phone call</option>
            <option value="text message">text message</option>
            </select>
            <h4><strong>ITEM DETAILS</strong></h4>
            <input maxlength="200" id="id_item_description" name="item_description"  value="{{ form.item_description.value }}" type="text" placeholder="item description"/><br>
            <input maxlength="100" id="id_item_location" style="margin-top: 7px"  name="item_location"  type="text" placeholder="location found"/><br>
        </div>
        <div>        
            <input type="image" name="submit" src="/static/img/Button_Im Done.png" alt="Submit" />
        </div> 
        </form>
    </div>
</div>
{% endblock content %}

transition/templates/googlecb48235008046c8e.html
google-site-verification: googlecb48235008046c8e.html

transition/templates/home.html
{% extends "base.html" %}

{% block content %}

<!-- Begin slider -->
<div class="span12">
  <div class="flexslider-container">
    <div class="flexslider">
            <ul class="slides">

          <li>
            <a href="http://store.rockettags.com/collections/all">
              <img src="//cdn.shopify.com/s/files/1/0504/5549/t/2/assets/slideshow_1.jpg?1247" alt="Luggage Tag" />
            </a>
            <!--
            <div class="flex-text1">
                <span class="flex-text1-bold">BETTER<br>PROTECT</span><br>
                <span class="flex-text1-normal">YOUR<br>VALUABLES</span>
            </div>
            -->
          </li>

          <li>
            <a href="http://store.rockettags.com//collections/all">
              <img src="//cdn.shopify.com/s/files/1/0504/5549/t/2/assets/slideshow_2.jpg?1247" alt="" />
            </a>
            <!--
            <div class="flex-text2">                
                <span class="flex-text2-normal" >THE<br>TRUSTED</span><br>
                <span class="flex-text2-bold" >LOST and<br>FOUND<br></span>
                <span class="flex-text2-normal" >SOLUTION</span>
            </div>
            -->
          </li>

          <li>
            <a href="http://store.rockettags.com//collections/all">
              <img src="//cdn.shopify.com/s/files/1/0504/5549/t/2/assets/slideshow_3.jpg?1247" alt="" />
            </a>
            <!--
            <div class="flex-text3">                
                <span class="flex-text3-normal" >PROTECT THOSE</span><br>
                <span class="flex-text3-bold" >PRECIOUS<br>MEMORIES</span>
            </div>
            -->
          </li>

          <li>
            <a href="http://store.rockettags.com//collections/all">
              <img src="//cdn.shopify.com/s/files/1/0504/5549/t/2/assets/slideshow_4.jpg?1247" alt="" />
            </a>
            <!--
            <div class="flex-text4">                
                <span class="flex-text4-bold" >YOUR BEST<br>CHANCE</span><br>
                <span class="flex-text4-normal" >OF HAVING YOUR</span><br>
                <span class="flex-text4-normal" >LOST VALUABLES<br>RETURNED</span>
            </div>
            -->
          </li>
 
      </ul>
      <div class="flex-controls"></div>
    </div>
  </div>
</div>
<!-- End slider -->
{% endblock content %}

transition/templates/myrockettags.html
{% extends "base.html" %}

{% block content %}

<div class="wizard row">
    <div class="span4">
        <div>        
            <h1><strong>MyRocket&shy;Tags</strong></h1>                             
            <p>Log in to MyRocketTags to access and edit your acccount information.<br>
            Remember, your username is your email address and your password is any RocketTag ID associated with your account.</p> 
        </div>
    </div>
    <div id="my-rocket-tags" class="span8 orange_box tl" >
        <form id="myrockettags" action="" method="post">{% csrf_token %}
        <div style="padding: 20px;" >
            <span class="txt1">personal details</span><br><br>  
            <div class="clearfix" style="padding-bottom: 20px;">
                <div class="myrockettags_left">
                    <span class="txt3" ><strong>email:</strong></span>
                </div>
                <div class="myrockettags_right">
                    <input style="border: 0; padding: 0; -moz-border-radius:0; -webkit-border-radius:0; border-radius:0; -moz-box-shadow: none; -webkit-box-shadow: none; box-shadow: none; height: 16px; background-color: #f37528; color: #ffffff; font-weight:700;" id="id_email" name="email" type="text" value="{{ user.email }}"/>{% if update_msg %}<img style="display: none;" id="flash" src="/static/img/mini_yes.png" width="25" height="18">{% endif %}<br>
                    <span class="txt4">select and retype to change email address <a class="txt4" style="text-decoration: underline;" id="update_email" href=".">click to save changes</a></span><br>    
                    <span class="oj_white"><strong>{{ form.email.errors.as_text }}</strong></span><br>
                </div>
            </div>              
            <span class="txt1">registered RocketTag IDs</span><br><br> 
            <div class="clearfix"> 
                <div class="clearfix" style="float: left">
                    <div class="clearfix">
                        <div style="float: left; min-width: 120px;">
                            <span class="txt2" style="text-decoration: underline;"><strong>ID</strong></span>
                        </div>
                        <div style="float: right; width: 75px;">                    
                            <span class="txt2" style="text-decoration: underline;"><strong>date&nbsp;registered</strong></span>
                        </div>
                    </div>   
                    {% for item in combined %}
                        <div class="clearfix">
                            <div style="float: left; min-width: 120px;">
                                <span class="txt3"><strong>{{ item.0 }}</strong></span>
                            </div>
                            <div style="float: right; width: 75px;">                    
                                <span class="txt3"><strong>{{ item.1|date:"d/m/y" }}</strong></span>
                            </div>
                        </div>   
                    {% endfor %}
                </div>
                
                <div style="float: right">
                    <a href="http://store.rockettags.com/collections/all"><img src="/static/img/get more tags button.png" /></a>
                </div>
            </div>
        </div>       
        </form>
    </div>
</div>

{% endblock content %}

transition/templates/promo.html
<!DOCTYPE html>
<html>
  <head>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <style>

      #logo {
        padding-top: 20px;
      }
      a {
        color: white;
      }
      a:hover {
        color: white;
        text-decoration: underline;
      }
      .oj_white { 
        font-size:14px; 
        line-height:16px; 
        color: white;
      }  

      .logged {
        color: white;
        font-size: 0.8em;
      }

      .custom-center {
        margin: auto;
      }

      input[type="image"] {
        padding: 30px 0 0;
      }

      h1 {
        font-weight: 900;
        padding-bottom: 30px;
      }

      img {
        padding-bottom: 20px;
      }

      h1, p {
        color: white;
      }

      p {
        font-size: 1.2em;
        padding: 25px 0 25px;
      }

      body {
        background-color: #f37528;
        font-family: Helvetica, Arial, sans-serif;
      }

    </style>
  </head>
  <body>
    <div class="container">

        <div class="row">
          <div class="col-xs-8 col-xs-offset-2 col-md-4 col-md-offset-4">
            <img id="logo" class="img-responsive custom-center" src="/static/img/logo-promo-page.png" alt="RocketTags - The Trusted Lost and Found Tag Solution">
          </div>
          
          <div class="col-xs-2 col-md-4">
            {% if campaign_promo %}
            <span class="logged">{{ request.user.email }} {% if request.user.email %}<a href="/user_logout/">logout</a>{% endif %}</span><br>
            <span class="logged">sent: {{ customer_email }}</span>
            {% endif %}
          </div>
        </div>

        <div class="row">
          <div class="col-xs-8 col-xs-offset-2 col-md-4 col-md-offset-4  ">
            <img class="img-responsive" src="/static/img/special-offer.png" alt="Special Offer!"> 
          </div>        
        </div>

        <div class="row">
          <div class="col-xs-8 col-xs-offset-2 col-md-4 col-md-offset-4 ">
            <p>Fill out your details below and we will email you our latest offer. Remember its only valid for a limited time so be quick and make the most of it!</p>
          </div>        
        </div>

        <div class="row">    
          <div class="col-xs-8 col-xs-offset-2 col-md-4 col-md-offset-4  ">             
            <div class="form-group">
              <form method="POST">{% csrf_token %}
              {{ form.email }}  
              <span id="id_email_error" class="oj_white"><strong>{{ form.email.errors.as_text }}</strong></span>            
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-xs-8 col-xs-offset-2 col-md-4 col-md-offset-4  ">
            <input class="center-block" type="image" name="submit" src="/static/img/button-im-finished.png" alt="Submit">
            </form>
          </div>
        </div>
    </div>
  </body>
</html>

transition/templates/register_tag_1.html
{% extends "base.html" %}

{% block content %}

<div class="wizard row">   
    <div class="span4">
        <div>        
            <h1><strong>register</strong> a Rocket&shy;Tag</h1>                             
            <p>Great, you have a new set of RocketTags to register.</p>
            <p>Simply enter the unique RocketTag ID found on one of your RocketTags below to get started!</p>
            <p>If you have more than one set of RocketTags to register then you will need to repeat this process for each set.</p>
        </div>
    </div>
    <div class="span8 orange_box tc" >
        <form action="" method="post">{% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        <div>
            <input id="id_code" name="code" type="text" maxlength="10" value="{{ form.code.value }}" placeholder="Enter your RocketTag ID here"/><br>
            <span class="oj_white"><strong>{{ form.code.errors.as_text }}</strong></span>
        </div>       
        <div>
            <input type="image" name="submit" src="/static/img/Button_Lets Do This.png" alt="Submit" />
        </div>
        </form>
    </div>
</div>

{% endblock content %}

transition/templates/register_tag_2.html
{% extends "base.html" %}

{% block content %}

<div class="wizard row">   
    <div class="span4">
        <div>        
            <h1><strong>Registration</strong> details</h1>                             
            <p>Please enter your email address</p>
        </div>
    </div>
    <div class="span8 orange_box tc" >
        <form action="" method="post">{% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        <div>
            <input id="id_email" maxlength="100" name="email" type="text" placeholder="Your Email"/><br>
            <input id="id_email2" maxlength="100" style="margin-top: 7px" name="email2" type="text" placeholder="Confirm Your Email"/><br>                                
            <span class="oj_white"><strong>{{ form.non_field_errors.as_text }}</strong></span>
        </div>
        <div>            
            <input type="image" name="submit" src="/static/img/Button_Lets Do This.png" alt="Submit" />
        </div>
        </form>
    </div>
</div>

{% endblock content %}

transition/templates/register_tag_4.html
{% extends "base.html" %}

{% block content %}

<div class="wizard row">   
    <div class="span4">
        <div>        
            <h1><strong>Registration</strong> process is complete.</h1>     
            <p>View and manage your details in the MyRocketTags section of the website at any time using the details below</p>
            <p>Username = Your Email<br>
            Password = Any RocketTags ID already registered to your account</p>
        </div>
    </div>
    <div id="register-tag-4" class="span8 orange_box tc">
        <div>
            <img src="/static/img/Thumbs Up Graphic.png" />
        </div>
        <div>
            <a href="http://store.rockettags.com"><img src="/static/img/Button_All Done.png" /></a>                
        </div> 
    </div>
</div>

{% endblock content %}

transition/templates/test_tag_1.html
{% extends "base.html" %}

{% block content %}

<div class="wizard row">
    <div class="span4">
        <div>        
            <h1><strong>test</strong> a Rocket&shy;Tag</h1>                             
            <p>Have a new RocketTag to test? then enter the RocketTag ID in the box below and we will send you an email to confirm that everything is working as it should.</p>
            <p>Go for it!</p>
        </div>
    </div>
    <div class="span8 orange_box tc">    
        <form action="" method="post">{% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        <div>
            <input id="id_code" name="code" type="text" placeholder="Enter your RocketTag ID here" maxlength="10"/><br>
            <span class="oj_white"><strong>{{ form.code.errors.as_text }}</strong></span>
        </div>
        <div>
            <input type="image" name="submit" src="/static/img/Button_Lets Do This.png" alt="Submit" />                
        </div>
        </form>
    </div>
</div>

{% endblock content %}